---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]

suites:
- name: redisio
  driver_config:
    network:
    - ["public_network", {ip: "192.168.1.217"}]
  run_list:
  - recipe[redisio]
  - recipe[redisio::enable]
  attributes:
